# Generated by Django 4.2.6 on 2023-11-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
