# Generated by Django 4.2.6 on 2024-03-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userbase_collateral'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='cetizenship',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userbase',
            name='pan_number',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
    ]
