# Generated by Django 4.2.6 on 2024-03-11 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_userbase_cetizenship_userbase_pan_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbase',
            old_name='cetizenship',
            new_name='citizenship',
        ),
    ]
