# Generated by Django 4.2.6 on 2024-03-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_cetizenship_userbase_citizenship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='citizenship',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
