# Generated by Django 4.2.6 on 2023-12-03 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='auction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_listing', to='main_app.auction'),
        ),
        migrations.AlterField(
            model_name='product',
            name='actual_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
