# Generated by Django 4.2.6 on 2024-03-05 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_usersearch_userbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbid',
            name='category',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='main_app.category'),
            preserve_default=False,
        ),
    ]
