# Generated by Django 4.2.6 on 2024-03-11 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0010_alter_finalorder_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='winner',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'pending'), ('paid and shipped', 'paid and shipped')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'pending'), ('paid and shipped', 'paid and shipped')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
