# Generated by Django 4.2.6 on 2024-03-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_auction_winner_alter_finalorder_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='marked_price',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
            preserve_default=False,
        ),
    ]
